; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3_wroom]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
upload_speed = 921600
monitor_speed = 115200
lib_deps = 
	adafruit/Adafruit NeoPixel@^1.15.5
	tkjelectronics/Kalman Filter Library@^1.0.2
	plerup/EspSoftwareSerial@^8.2.0
